/*
 * generated by Xtext
 */
package edu.iastate.cs.boa;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BoaRuntimeModule extends edu.iastate.cs.boa.AbstractBoaRuntimeModule {

}
