/*
* generated by Xtext
*/
package edu.iastate.cs.boa;

/**
 * Initialization support for running Xtext languages
 * without equinox extension registry
 */
public class BoaStandaloneSetup extends BoaStandaloneSetupGenerated {
	public static void doSetup() {
		new BoaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
