/*
 * generated by Xtext
 */
package edu.iastate.cs.boa.ui.contentassist

import edu.iastate.cs.boa.ui.contentassist.AbstractBoaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BoaProposalProvider extends AbstractBoaProposalProvider {
}
