/*
 * generated by Xtext
 */
package edu.iastate.cs.boa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BoaUiModule extends edu.iastate.cs.boa.ui.AbstractBoaUiModule {
	public BoaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
